### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by tromp** [kspalaiologos/blc-mb#1]
On my iMac running macOS Cataline 10.15.7,
having built f20 with $ clang -O3 -march=native -mtune=native fast20.c -o f20
I get
$ echo "*Hello" | ./f20 blc.mb
Bus error: 10
Actually, it's not dependent on the input:
$ ./f20 blc.mb
Bus error: 10

For reference:
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ shasum blc.mb fast20.c
07440c678b89e0a141d3cf513549b327236c905e  blc.mb
16760b629f1e09e0ce539b401726067ba39a911d  fast20.c

PS: Thanks for making yet another interpreter for my little language!

**Comment by iczelia** [comment]
Hi,
Unfortunately fast20 is not guaranteed to work on Darwin. I have developed and tested it with a Linux machine, could you try using a Linux machine instead? I do not own an Apple-made machine, hence I can't help with the issue.
Thanks for your feedback!

**Comment by tromp** [comment]
I also tried the "standard" Malbolge interpreter from https://www.lscheffer.com/malbolge_interp.html
on various example programs from https://github.com/nstarke/malbolge-examples:

$ ./mbi hello-world.mb ; echo
HEllO WORld
$ ./mbi hello-world2.mb ; echo
Hello World!

But it's useless for the much bigger blc engine:

$ ./mbi blc.mb
input file too long

fast20 seems to have problems with those hello worlds:

$ ./f20 hello-world.mb 
H?? 
$ ./f20 hello-world2.mb 
H%%((

Do those work fine for you on Linux?
Unfortunately I don't have access to a Linux machine.

**Comment by iczelia** [comment]
The fast20 interpreter actually runs Malbolge Unshackled (a variant that allows for unbounded memory access). Try https://lutter.cc/unshackled/Unshackled-20.c, but prepare for this to take more than half an hour on your code :-).

**Comment by iczelia** [comment]
OTOH: The fast20 interpreter does nasty things in order to speed up the runtime of Malbolge code. For instance, we map a large region of memory marked as read-only and trap segmentation faults to then fill the memory with the pattern that is required by the Malbolge Unshackled specification, promptly calling mprotect to mark the page as RW. It's likely that MacOS does not support that.

**Comment by tromp** [comment]
Thanks for elaborating. I will have to shelve my plans to try BLC on Malbolge until I get access to a Linux machine...
